# Generated by Django 5.1.2 on 2025-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20250802_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для категории (рекомендуется 400x300px)', null=True, upload_to='categories/', verbose_name='Картинка'),
        ),
    ]
