# Generated by Django 5.1.2 on 2025-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NLPers.ru', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, help_text='Краткое описание сайта для SEO', verbose_name='Описание сайта')),
                ('background_image', models.ImageField(blank=True, help_text='Основное фоновое изображение сайта', null=True, upload_to='site_backgrounds/', verbose_name='Фоновое изображение')),
                ('background_overlay_opacity', models.FloatField(default=0.7, help_text='От 0.0 (полностью прозрачно) до 1.0 (полностью непрозрачно)', verbose_name='Прозрачность наложения')),
                ('header_background_color', models.CharField(default='#1a1a1a', help_text='HEX цвет для фона меню', max_length=7, verbose_name='Цвет фона шапки')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/', verbose_name='Логотип сайта')),
                ('favicon', models.ImageField(blank=True, help_text='Иконка сайта (16x16 или 32x32 пикселя)', null=True, upload_to='site_favicons/', verbose_name='Favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ссылки на соцсети в формате JSON', verbose_name='Социальные сети')),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics, Яндекс.Метрика и т.д.', verbose_name='Код аналитики')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Включить для технических работ', verbose_name='Режим обслуживания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
