# Generated by Django 5.1.2 on 2025-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Изображение для превью файла', null=True, upload_to='archive/thumbnails/', verbose_name='Превью'),
        ),
    ]
